name = "DiscretePredictors"
uuid = "a1b8beaa-0f25-52fa-b34f-c7db7ae101e8"
keywords = ["prediction"]
license = "MIT"
desc = "A collection of discrete symbol predictors"
version = "1.0.1"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]